INSERT INTO pairings (wine_style, food_category, food_name, match_quality, notes) VALUES
  ('Bordeaux Rouge', 'red meat', 'Entrecôte grillée', 'classic', 'Le tanin du Bordeaux sublime le gras de la viande'),
  ('Bordeaux Rouge', 'red meat', 'Agneau rôti', 'classic', NULL),
  ('Bordeaux Rouge', 'cheese', 'Comté affiné', 'good', NULL),
  ('Bourgogne Rouge', 'red meat', 'Bœuf Bourguignon', 'classic', NULL),
  ('Bourgogne Rouge', 'poultry', 'Poulet rôti', 'classic', NULL),
  ('Bourgogne Rouge', 'cheese', 'Époisses', 'good', NULL),
  ('Bourgogne Blanc', 'seafood', 'Saint-Jacques poêlées', 'classic', NULL),
  ('Bourgogne Blanc', 'seafood', 'Homard beurre blanc', 'classic', NULL),
  ('Bourgogne Blanc', 'cheese', 'Camembert', 'good', NULL),
  ('Champagne', 'seafood', 'Huîtres', 'classic', NULL),
  ('Champagne', 'appetizer', 'Amuse-bouches', 'classic', NULL),
  ('Champagne', 'dessert', 'Tarte aux fraises', 'good', NULL),
  ('Alsace Riesling', 'seafood', 'Choucroute de la mer', 'classic', NULL),
  ('Alsace Riesling', 'poultry', 'Coq au Riesling', 'classic', NULL),
  ('Côtes du Rhône Rouge', 'red meat', 'Daube provençale', 'classic', NULL),
  ('Côtes du Rhône Rouge', 'vegetables', 'Ratatouille', 'good', NULL),
  ('Sancerre', 'seafood', 'Chèvre frais', 'classic', NULL),
  ('Sancerre', 'seafood', 'Moules marinières', 'good', NULL),
  ('Sauternes', 'dessert', 'Foie gras', 'classic', 'Accord sucré-salé emblématique'),
  ('Sauternes', 'dessert', 'Tarte Tatin', 'classic', NULL);
