-- Expanded pairings database

INSERT INTO pairings (wine_style, grape_hint, food_category, food_name, match_quality, notes) VALUES

-- VIANDES ROUGES
('Bordeaux rouge', ARRAY['Cabernet Sauvignon', 'Merlot'], 'viandes_rouges', 'Entrecôte grillée', 'classic', 'Les tanins du Bordeaux structurent parfaitement la richesse de la viande.'),
('Côte du Rhône rouge', ARRAY['Syrah', 'Grenache'], 'viandes_rouges', 'Côte de bœuf', 'classic', 'La puissance du Syrah accompagne idéalement ce morceau généreux.'),
('Barolo', ARRAY['Nebbiolo'], 'viandes_rouges', 'Bœuf braisé', 'classic', 'Le Barolo et sa structure tannique subliment les longues cuissons.'),
('Rioja Reserva', ARRAY['Tempranillo'], 'viandes_rouges', 'Rôti de bœuf', 'classic', 'La fraîcheur acidulée du Tempranillo équilibre la viande rôtie.'),
('Cahors', ARRAY['Malbec'], 'viandes_rouges', 'Magret de canard', 'classic', 'Le Malbec de Cahors, charnu et épicé, s''allie parfaitement au canard.'),
('Châteauneuf-du-Pape rouge', ARRAY['Grenache', 'Syrah'], 'viandes_rouges', 'Gigot d''agneau', 'classic', 'Un grand classique provençal, les arômes épicés se marient à merveille.'),
('Pomerol', ARRAY['Merlot'], 'viandes_rouges', 'Tournedos Rossini', 'classic', 'Le velouté du Merlot accompagne à merveille le foie gras et la truffe.'),
('Saint-Émilion', ARRAY['Merlot', 'Cabernet Franc'], 'viandes_rouges', 'Pavé de bœuf aux champignons', 'good', 'Les notes terreuses du vin se marient aux champignons.'),
('Bourgogne rouge', ARRAY['Pinot Noir'], 'viandes_rouges', 'Canard à l''orange', 'good', 'La finesse du Pinot Noir souligne la douceur et l''acidité de la sauce.'),
('Madiran', ARRAY['Tannat'], 'viandes_rouges', 'Cassoulet', 'classic', 'Le Tannat robuste tient tête au cassoulet riche et gras.'),
('Bergerac rouge', ARRAY['Cabernet Sauvignon', 'Merlot'], 'viandes_rouges', 'Daube de bœuf', 'good', 'Les arômes de fruits rouges équilibrent la richesse du plat mijoté.'),
('Syrah Pays d''Oc', ARRAY['Syrah'], 'viandes_rouges', 'Brochettes d''agneau', 'good', 'La Syrah épicée du sud de la France s''accorde bien aux grillades.'),

-- VIANDES BLANCHES
('Bourgogne blanc', ARRAY['Chardonnay'], 'viandes_blanches', 'Poulet rôti', 'classic', 'Un grand classique : le Chardonnay bourguignon sublime la simplicité du poulet.'),
('Meursault', ARRAY['Chardonnay'], 'viandes_blanches', 'Suprême de volaille à la crème', 'classic', 'La richesse du Meursault accompagne parfaitement les sauces crémeuses.'),
('Pinot Gris Alsace', ARRAY['Pinot Gris'], 'viandes_blanches', 'Veau Marengo', 'good', 'Le Pinot Gris ample et légèrement épicé s''accorde bien au veau en sauce.'),
('Pouilly-Fuissé', ARRAY['Chardonnay'], 'viandes_blanches', 'Blanquette de veau', 'classic', 'L''onctuosité du Pouilly-Fuissé accompagne idéalement la sauce blanche.'),
('Côtes du Rhône blanc', ARRAY['Viognier', 'Roussanne'], 'viandes_blanches', 'Poulet aux olives', 'good', 'Les arômes floraux du Viognier complètent les saveurs méditerranéennes.'),
('Sancerre rouge', ARRAY['Pinot Noir'], 'viandes_blanches', 'Rôti de veau', 'good', 'La légèreté du Pinot Noir de Sancerre s''accorde bien aux viandes délicates.'),
('Beaujolais Villages', ARRAY['Gamay'], 'viandes_blanches', 'Andouillette grillée', 'classic', 'Un accord bistrot authentique, léger et gourmand.'),
('Chablis Premier Cru', ARRAY['Chardonnay'], 'viandes_blanches', 'Côte de veau grillée', 'good', 'La minéralité de Chablis contraste agréablement avec la viande tendre.'),
('Mâcon blanc', ARRAY['Chardonnay'], 'viandes_blanches', 'Lapin à la moutarde', 'classic', 'Le Mâcon fruité équilibre le piquant de la moutarde.'),
('Pinot Noir Alsace', ARRAY['Pinot Noir'], 'viandes_blanches', 'Cochon de lait rôti', 'good', 'Légèreté et fruité s''accordent à la tendreté du porcelet.'),

-- POISSONS
('Chablis', ARRAY['Chardonnay'], 'poissons', 'Filet de sole meunière', 'classic', 'La minéralité iodée de Chablis est faite pour le poisson de mer.'),
('Muscadet Sèvre et Maine', ARRAY['Melon de Bourgogne'], 'poissons', 'Sardines grillées', 'classic', 'Le Muscadet sur lie, vif et salin, est l''accord idéal pour les poissons gras.'),
('Pouilly-Fumé', ARRAY['Sauvignon Blanc'], 'poissons', 'Saumon gravlax', 'classic', 'Les notes fumées du Sauvignon accompagnent parfaitement le saumon.'),
('Alsace Riesling', ARRAY['Riesling'], 'poissons', 'Truite aux amandes', 'classic', 'La fraîcheur et l''acidité du Riesling subliment les poissons de rivière.'),
('Bourgogne blanc', ARRAY['Chardonnay'], 'poissons', 'Saint-Jacques poêlées', 'classic', 'La rondeur du Chardonnay accompagne à merveille la noix de Saint-Jacques.'),
('Picpoul de Pinet', ARRAY['Picpoul'], 'poissons', 'Thon snacké', 'good', 'La vivacité du Picpoul s''accorde bien aux thonidés.'),
('Sancerre blanc', ARRAY['Sauvignon Blanc'], 'poissons', 'Bar grillé', 'classic', 'L''élégance du Sancerre met en valeur le bar sauvage.'),
('Champagne Blanc de Blancs', ARRAY['Chardonnay'], 'poissons', 'Sole grillée au beurre blanc', 'classic', 'La finesse des bulles et l''acidité accompagnent la délicatesse du plat.'),
('Coteaux du Languedoc blanc', ARRAY['Picpoul', 'Vermentino'], 'poissons', 'Daurade royale', 'good', 'Les vins du Languedoc accompagnent bien les poissons méditerranéens.'),
('Entre-deux-Mers', ARRAY['Sauvignon Blanc', 'Sémillon'], 'poissons', 'Quenelles de brochet', 'good', 'La fraîcheur acidulée du vin équilibre la sauce Nantua.'),
('Vermentino de Corse', ARRAY['Vermentino'], 'poissons', 'Loup de mer', 'classic', 'Un accord méditerranéen parfait, iodé et minéral.'),

-- FRUITS DE MER
('Muscadet', ARRAY['Melon de Bourgogne'], 'fruits_de_mer', 'Huîtres plates', 'classic', 'L''accord ultime : sel, iode et minéralité.'),
('Champagne Brut', ARRAY['Chardonnay', 'Pinot Noir'], 'fruits_de_mer', 'Plateau de fruits de mer', 'classic', 'Les bulles et l''acidité nettoient le palais entre chaque bouchée.'),
('Chablis Grand Cru', ARRAY['Chardonnay'], 'fruits_de_mer', 'Homard à l''armoricaine', 'classic', 'La puissance et la minéralité du Chablis Grand Cru tient tête au homard.'),
('Alsace Riesling', ARRAY['Riesling'], 'fruits_de_mer', 'Crevettes grillées', 'good', 'La vivacité du Riesling s''accorde bien aux crustacés.'),
('Roussette de Savoie', ARRAY['Altesse'], 'fruits_de_mer', 'Fondue de moules', 'good', 'La fraîcheur alpine de la Roussette accompagne bien les moules.'),
('Picpoul de Pinet', ARRAY['Picpoul'], 'fruits_de_mer', 'Moules marinières', 'classic', 'Le Picpoul vif et salin est fait pour les moules de Méditerranée.'),
('Gros Plant du Pays Nantais', ARRAY['Folle Blanche'], 'fruits_de_mer', 'Bigorneaux et bulots', 'classic', 'L''acidité tranchante du Gros Plant nettoie parfaitement les coquillages.'),
('Sancerre blanc', ARRAY['Sauvignon Blanc'], 'fruits_de_mer', 'Coquilles Saint-Jacques gratinées', 'good', 'La minéralité du Sancerre s''accorde aux Saint-Jacques en gratin.'),
('Pouilly-Fumé', ARRAY['Sauvignon Blanc'], 'fruits_de_mer', 'Langoustines rôties', 'classic', 'Les notes fumées et herbacées subliment les langoustines.'),
('Champagne Rosé', ARRAY['Pinot Noir', 'Chardonnay'], 'fruits_de_mer', 'Homard grillé', 'classic', 'L''élégance du Champagne rosé accompagne parfaitement la chair du homard.'),

-- FROMAGES
('Sauternes', ARRAY['Sémillon', 'Sauvignon Blanc'], 'fromages', 'Roquefort', 'classic', 'Le sucre du Sauternes tempère le sel et la puissance du Roquefort.'),
('Bourgogne rouge', ARRAY['Pinot Noir'], 'fromages', 'Époisses', 'classic', 'Un accord régional indissociable, puissant et harmonieux.'),
('Alsace Gewurztraminer', ARRAY['Gewurztraminer'], 'fromages', 'Munster', 'classic', 'L''Alsace unit ses deux trésors : le Munster et le Gewurztraminer.'),
('Porto LBV', ARRAY['Touriga Nacional'], 'fromages', 'Stilton', 'classic', 'L''accord britannique par excellence, sucré-salé inoubliable.'),
('Sancerre blanc', ARRAY['Sauvignon Blanc'], 'fromages', 'Chèvre frais', 'classic', 'La Loire réunit ses deux emblèmes : chèvre et Sauvignon.'),
('Champagne Brut', ARRAY['Chardonnay', 'Pinot Noir'], 'fromages', 'Brillat-Savarin', 'classic', 'Les bulles et l''acidité tranchent dans le gras du fromage triple-crème.'),
('Beaujolais Villages', ARRAY['Gamay'], 'fromages', 'Saint-Marcellin', 'good', 'Le fruité du Beaujolais accompagne agréablement ce fromage crémeux.'),
('Châteauneuf-du-Pape rouge', ARRAY['Grenache'], 'fromages', 'Comté 24 mois', 'good', 'La puissance et les arômes grillés du Comté s''accordent bien.'),
('Chablis', ARRAY['Chardonnay'], 'fromages', 'Chaource', 'classic', 'Un accord régional bourguignon très réussi.'),
('Bourgogne Aligoté', ARRAY['Aligoté'], 'fromages', 'Fromage blanc', 'good', 'La fraîcheur de l''Aligoté accompagne légèrement le fromage blanc.'),
('Jurançon sec', ARRAY['Gros Manseng'], 'fromages', 'Ossau-Iraty', 'classic', 'Deux spécialités du Pays Basque qui s''accordent parfaitement.'),
('Côtes du Jura', ARRAY['Savagnin'], 'fromages', 'Comté', 'classic', 'L''accord jurassien par excellence, le vin jaune sublime le Comté.'),
('Banyuls', ARRAY['Grenache'], 'fromages', 'Chocolat noir 70%', 'classic', 'Le Banyuls doux et oxydé accompagne idéalement le chocolat puissant.'),

-- CHARCUTERIE
('Beaujolais Villages', ARRAY['Gamay'], 'charcuterie', 'Saucisson sec', 'classic', 'L''accord bistrot parfait, fruité et gourmand.'),
('Côtes du Rhône rouge', ARRAY['Grenache', 'Syrah'], 'charcuterie', 'Rosette de Lyon', 'good', 'Les épices du vin accompagnent bien la charcuterie lyonnaise.'),
('Alsace Pinot Gris', ARRAY['Pinot Gris'], 'charcuterie', 'Choucroute garnie', 'classic', 'Le Pinot Gris ample équilibre parfaitement la choucroute traditionnelle.'),
('Sancerre rouge', ARRAY['Pinot Noir'], 'charcuterie', 'Jambon persillé', 'classic', 'La légèreté du Pinot Noir s''accorde bien à cette terrine bourguignonne.'),
('Madiran', ARRAY['Tannat'], 'charcuterie', 'Jambon de Bayonne', 'classic', 'Un accord gascon authentique et puissant.'),
('Cahors', ARRAY['Malbec'], 'charcuterie', 'Confit de canard', 'classic', 'Le Malbec et le confit, deux emblèmes du Périgord qui se complètent.'),
('Champagne Brut', ARRAY['Pinot Noir', 'Chardonnay'], 'charcuterie', 'Foie gras mi-cuit', 'classic', 'L''acidité du Champagne tranche dans le gras somptueux du foie gras.'),
('Bergerac blanc', ARRAY['Sémillon', 'Sauvignon Blanc'], 'charcuterie', 'Foie gras poêlé', 'good', 'La douceur légère du Bergerac moelleux équilibre le foie gras.'),
('Pinot Noir Alsace', ARRAY['Pinot Noir'], 'charcuterie', 'Tarte flambée', 'classic', 'Le Pinot Noir léger d''Alsace accompagne parfaitement la flammekueche.'),

-- CUISINE ITALIENNE
('Barolo', ARRAY['Nebbiolo'], 'cuisine_italienne', 'Osso Buco', 'classic', 'Le Barolo, roi du Piémont, accompagne ce grand plat milanais.'),
('Chianti Classico', ARRAY['Sangiovese'], 'cuisine_italienne', 'Lasagnes bolognaise', 'classic', 'L''acidité du Sangiovese tranche dans la richesse des lasagnes.'),
('Brunello di Montalcino', ARRAY['Sangiovese'], 'cuisine_italienne', 'Bistecca alla Fiorentina', 'classic', 'Un accord toscan d''exception pour cette côte de bœuf florentine.'),
('Amarone della Valpolicella', ARRAY['Corvina', 'Rondinella'], 'cuisine_italienne', 'Risotto aux truffes', 'classic', 'La richesse de l''Amarone accompagne la puissance aromatique de la truffe.'),
('Pinot Grigio', ARRAY['Pinot Gris'], 'cuisine_italienne', 'Risotto aux fruits de mer', 'good', 'La légèreté et la fraîcheur du Pinot Grigio accompagnent ce risotto.'),
('Soave', ARRAY['Garganega'], 'cuisine_italienne', 'Carpaccio de veau', 'good', 'La douceur du Soave s''accorde bien à la délicatesse du carpaccio.'),
('Prosecco', ARRAY['Glera'], 'cuisine_italienne', 'Antipasti', 'classic', 'Les bulles légères du Prosecco accompagnent à merveille les antipasti.'),
('Barbera d''Asti', ARRAY['Barbera'], 'cuisine_italienne', 'Pizza Margherita', 'classic', 'La Barbera acidulée est l''accord parfait pour la pizza tomate.'),
('Vermentino di Sardegna', ARRAY['Vermentino'], 'cuisine_italienne', 'Pâtes aux palourdes', 'classic', 'La fraîcheur iodée du Vermentino sublime les pâtes aux vongole.'),
('Ripasso Valpolicella', ARRAY['Corvina'], 'cuisine_italienne', 'Pâtes à la carbonara', 'good', 'La rondeur du Ripasso équilibre la richesse de la carbonara.'),

-- CUISINE ESPAGNOLE
('Rioja Reserva', ARRAY['Tempranillo'], 'cuisine_espagnole', 'Paella valenciana', 'classic', 'Un accord ibérique naturel, le Rioja accompagne parfaitement la paella.'),
('Ribera del Duero', ARRAY['Tempranillo'], 'cuisine_espagnole', 'Cochon de lait ségovien', 'classic', 'Ce grand vin castillan accompagne le cochon de lait de Ségovie.'),
('Albariño', ARRAY['Albariño'], 'cuisine_espagnole', 'Pulpo a la gallega', 'classic', 'L''Albariño de Galice, frais et minéral, accompagne parfaitement le poulpe.'),
('Fino Sherry', ARRAY['Palomino'], 'cuisine_espagnole', 'Jamón ibérico', 'classic', 'Le Fino sec et salin sublime la complexité du jambon ibérique bellota.'),
('Cava Brut', ARRAY['Xarel·lo', 'Macabeo'], 'cuisine_espagnole', 'Tapas variées', 'classic', 'Le Cava pétillant accompagne légèrement toutes les tapas.'),
('Txakoli', ARRAY['Hondarrabi Zuri'], 'cuisine_espagnole', 'Pintxos', 'classic', 'Ce vin basque vif et perlant est fait pour les pintxos.'),
('Priorat', ARRAY['Grenache', 'Carignan'], 'cuisine_espagnole', 'Agneau au four', 'good', 'La puissance du Priorat accompagne bien les viandes rôties.'),

-- CUISINE ASIATIQUE
('Riesling Alsace', ARRAY['Riesling'], 'cuisine_asiatique', 'Poulet thaï au basilic', 'good', 'L''acidité et le fruité du Riesling équilibrent les épices thaïes.'),
('Gewurztraminer Alsace', ARRAY['Gewurztraminer'], 'cuisine_asiatique', 'Canard laqué pékinois', 'classic', 'Le Gewurztraminer exotique et épicé est fait pour la cuisine chinoise.'),
('Champagne Demi-Sec', ARRAY['Chardonnay', 'Pinot Noir'], 'cuisine_asiatique', 'Sushi et sashimi', 'good', 'Les bulles et la légère sucrosité accompagnent bien le poisson cru.'),
('Pinot Gris Alsace', ARRAY['Pinot Gris'], 'cuisine_asiatique', 'Porc au caramel vietnamien', 'good', 'La richesse aromatique du Pinot Gris accompagne les sauces sucrées-salées.'),
('Viognier', ARRAY['Viognier'], 'cuisine_asiatique', 'Curry de crevettes', 'good', 'Les arômes floraux et la rondeur du Viognier équilibrent le curry doux.'),
('Riesling demi-sec', ARRAY['Riesling'], 'cuisine_asiatique', 'Nems et rouleaux de printemps', 'good', 'Une légère sucrosité équilibre bien la sauce nuoc-mâm.'),
('Gewurztraminer vendanges tardives', ARRAY['Gewurztraminer'], 'cuisine_asiatique', 'Cuisine indienne épicée', 'good', 'La douceur et les arômes exotiques du Gewurztraminer domptent les épices.'),
('Champagne Brut', ARRAY['Chardonnay', 'Pinot Noir'], 'cuisine_asiatique', 'Raviolis japonais gyoza', 'acceptable', 'Les bulles et l''acidité accompagnent agréablement les gyoza.'),
('Muscadet', ARRAY['Melon de Bourgogne'], 'cuisine_asiatique', 'Poisson vapeur à la cantonaise', 'good', 'La légèreté et la neutralité du Muscadet accompagnent les cuissons vapeur.'),
('Condrieu', ARRAY['Viognier'], 'cuisine_asiatique', 'Poulet tikka masala', 'good', 'Le Condrieu floral et riche tient tête aux épices douces du tikka masala.'),

-- VEGETARIEN
('Sancerre blanc', ARRAY['Sauvignon Blanc'], 'vegetarien', 'Asperges vertes grillées', 'classic', 'Le Sauvignon Blanc est le seul vin qui accompagne vraiment les asperges.'),
('Chablis', ARRAY['Chardonnay'], 'vegetarien', 'Tarte aux poireaux', 'good', 'La minéralité de Chablis accompagne bien les légumes de saison.'),
('Pouilly-Fumé', ARRAY['Sauvignon Blanc'], 'vegetarien', 'Gaspacho andalou', 'good', 'La fraîcheur herbacée du Sauvignon Blanc complète le gaspacho.'),
('Beaujolais Villages', ARRAY['Gamay'], 'vegetarien', 'Gratin dauphinois', 'good', 'Le fruité léger du Beaujolais accompagne sans alourdir ce plat généreux.'),
('Rosé de Provence', ARRAY['Grenache', 'Cinsault'], 'vegetarien', 'Ratatouille', 'classic', 'Le rosé provençal est l''accord naturel pour la ratatouille.'),
('Viognier', ARRAY['Viognier'], 'vegetarien', 'Tarte aux courgettes', 'good', 'Les arômes floraux du Viognier s''accordent bien aux légumes d''été.'),
('Champagne Brut', ARRAY['Chardonnay'], 'vegetarien', 'Risotto aux champignons', 'good', 'La vivacité du Champagne tranche dans la richesse du risotto.'),
('Bourgogne Aligoté', ARRAY['Aligoté'], 'vegetarien', 'Œufs en meurette', 'classic', 'Un accord bourguignon traditionnel, simple et savoureux.'),
('Roussillon rouge', ARRAY['Grenache', 'Carignan'], 'vegetarien', 'Tajine de légumes', 'good', 'Les épices douces du tajine s''accordent aux vins du sud chauds et fruités.'),

-- DESSERTS
('Sauternes', ARRAY['Sémillon', 'Sauvignon Blanc'], 'desserts', 'Tarte Tatin', 'classic', 'Le Sauternes et la tarte aux pommes caramélisées, un accord de rêve.'),
('Champagne Demi-Sec', ARRAY['Chardonnay', 'Pinot Noir'], 'desserts', 'Charlotte aux fraises', 'classic', 'Le Champagne demi-sec accompagne idéalement les desserts aux fruits rouges.'),
('Muscat de Beaumes-de-Venise', ARRAY['Muscat'], 'desserts', 'Tarte aux abricots', 'classic', 'Les arômes de fleur d''oranger du Muscat subliment les abricots.'),
('Banyuls', ARRAY['Grenache'], 'desserts', 'Fondant au chocolat', 'classic', 'Le Banyuls doux-amer est l''accord parfait pour les desserts chocolatés.'),
('Sauternes', ARRAY['Sémillon'], 'desserts', 'Crème brûlée', 'classic', 'La vanille et la richesse du Sauternes accompagnent à merveille la crème brûlée.'),
('Moscato d''Asti', ARRAY['Muscat'], 'desserts', 'Fraises à la crème', 'classic', 'La légèreté perlante du Moscato accompagne délicatement les fraises.'),
('Jurançon moelleux', ARRAY['Gros Manseng', 'Petit Manseng'], 'desserts', 'Tarte aux poires', 'classic', 'La douceur exotique du Jurançon moelleux sublime la poire.'),
('Coteaux du Layon', ARRAY['Chenin Blanc'], 'desserts', 'Tarte aux mirabelles', 'classic', 'Le Chenin moelleux de Loire et les mirabelles, un accord du Grand Est.'),
('Rivesaltes ambré', ARRAY['Grenache Blanc', 'Macabeo'], 'desserts', 'Crème catalane', 'classic', 'Un accord roussillonnais traditionnel et délicieux.'),
('Porto Tawny', ARRAY['Touriga Nacional'], 'desserts', 'Tarte aux noix', 'classic', 'Les notes de noix et de caramel du Tawny accompagnent parfaitement.'),
('Gewurztraminer vendanges tardives', ARRAY['Gewurztraminer'], 'desserts', 'Tarte aux coings', 'classic', 'La richesse aromatique du Gewurztraminer VT sublime les coings.'),
('Champagne Brut', ARRAY['Chardonnay'], 'desserts', 'Macaron à la vanille', 'good', 'La fraîcheur du Champagne équilibre la douceur du macaron.'),

-- CUISINE FRANÇAISE BISTROT
('Beaujolais nouveau', ARRAY['Gamay'], 'cuisine_francaise', 'Steak-frites', 'classic', 'L''accord bistrot parisien par excellence.'),
('Bordeaux rouge', ARRAY['Cabernet Sauvignon', 'Merlot'], 'cuisine_francaise', 'Entrecôte bordelaise', 'classic', 'La sauce à la moelle sublime le Bordeaux et vice versa.'),
('Bourgogne rouge', ARRAY['Pinot Noir'], 'cuisine_francaise', 'Coq au vin', 'classic', 'Plat cuisiné au Bourgogne, servi avec le même vin, un classique intemporel.'),
('Côtes du Rhône rouge', ARRAY['Grenache', 'Syrah'], 'cuisine_francaise', 'Tian provençal', 'good', 'Les herbes de Provence du tian résonnent avec les garrigue du vin.'),
('Rosé de Provence', ARRAY['Grenache', 'Cinsault'], 'cuisine_francaise', 'Bouillabaisse', 'classic', 'Le rosé provençal sec accompagne la bouillabaisse marseillaise.'),
('Champagne Brut', ARRAY['Chardonnay', 'Pinot Noir'], 'cuisine_francaise', 'Soufflé au fromage', 'classic', 'La légèreté des bulles accompagne la légèreté du soufflé.'),
('Sancerre blanc', ARRAY['Sauvignon Blanc'], 'cuisine_francaise', 'Quiche lorraine', 'good', 'La fraîcheur du Sancerre tranche dans la richesse de la quiche.'),
('Côtes de Gascogne blanc', ARRAY['Colombard', 'Ugni Blanc'], 'cuisine_francaise', 'Salade landaise', 'classic', 'Le vin de Gascogne frais et fruité accompagne la salade du Sud-Ouest.'),
('Chablis Premier Cru', ARRAY['Chardonnay'], 'cuisine_francaise', 'Escargots de Bourgogne', 'classic', 'Un accord bourguignon parfait, le beurre persillé sublime le Chablis.'),
('Pinot Gris Alsace', ARRAY['Pinot Gris'], 'cuisine_francaise', 'Baeckeoffe', 'classic', 'Le Pinot Gris alsacien est le seul vin pour ce ragoût traditionnel.'),
('Muscadet', ARRAY['Melon de Bourgogne'], 'cuisine_francaise', 'Galette saucisse bretonne', 'classic', 'Un accord ligérien simple et authentique.');
